### ISSUE TITLE
评论区看不到了

### ISSUE THREAD

**Issue by starwaver** [ipcjs/bilibili-helper#1173]
最近几个月评论区显示不了，打开console会出现以下错误
![image](https://user-images.githubusercontent.com/7750800/223283856-b0e20219-7370-490a-bab6-94c5b731ce99.png)

```
1.video.d78d6e85da752e622f857a963ae79be916fe4c01.js:13 TypeError: window.commentContainer.find is not a function
    at s.loadComment (video.d78d6e85da752e622f857a963ae79be916fe4c01.js:1:58865)
    at s.loginLoaded (video.d78d6e85da752e622f857a963ae79be916fe4c01.js:1:53355)
    at mn.run (1.video.d78d6e85da752e622f857a963ae79be916fe4c01.js:13:27644)
    at hn (1.video.d78d6e85da752e622f857a963ae79be916fe4c01.js:13:25655)
    at Array.<anonymous> (1.video.d78d6e85da752e622f857a963ae79be916fe4c01.js:13:12347)
    at Yt (1.video.d78d6e85da752e622f857a963ae79be916fe4c01.js:13:11791)
Kt @ 1.video.d78d6e85da752e622f857a963ae79be916fe4c01.js:13
```

**Comment by luckyuptop** [comment]
+1

**Comment by zxy15647** [comment]
同样评论区不显示，还有出现标题多出A站独播、先跳转到银魂才返回当前番剧等问题

**Comment by starwaver** [comment]
最新的更新解决了
