### ISSUE TITLE
无限视频拉取失败

### ISSUE THREAD

**Issue by Cathyyin** [ipcjs/bilibili-helper#176]
## 描述

无限的拉取失败，然后16秒B站黑色小电视

## 日志

```
<!-- 复制来的日志，粘贴在这里 -->

```userscript.html?id=0ba05d47-bf94-40ba-9cca-5eb1fc2e3927:175 log: [解除B站区域限制 v6.8.2 (Tampermonkey)] run on: https://www.bilibili.com/bangumi/play/ep115394
userscript.html?id=0ba05d47-bf94-40ba-9cca-5eb1fc2e3927:175 debug: XMLHttpRequest的描述符: Object {writable: true, enumerable: false, configurable: true, value: function}
userscript.html?id=0ba05d47-bf94-40ba-9cca-5eb1fc2e3927:175 log: mode: default blocked_vip: undefined server: https://www.biliplus.com flv_prefer_ws: undefined remove_pre_ad: undefined readyState: loading isLogin: true isLoginBiliBili: true
userscript.html?id=0ba05d47-bf94-40ba-9cca-5eb1fc2e3927:175 log: /x/web-interface/nav Object {uname: "杏酱大小姐", isLogin: true, level: 5, vipType: 1, vipStatus: 1}
userscript.html?id=0ba05d47-bf94-40ba-9cca-5eb1fc2e3927:175 log: /season/user/status: {"code":0,"message":"success","result":{"area_limit":1,"ban_area_show":1,"follow":1,"paster":{"aid":0,"allow_jump":0,"cid":0,"duration":0,"type":0,"url":""},"pay":0,"pay_pack_paid":0,"sponsor":0,"watch_progress":{"last_ep_id":115393,"last_ep_index":"22","last_time":1348}}}
userscript.html?id=0ba05d47-bf94-40ba-9cca-5eb1fc2e3927:175 log: setAreaLimitSeason ep115394 true
userscript.html?id=0ba05d47-bf94-40ba-9cca-5eb1fc2e3927:175 log: player msg: 从代理服务器拉取视频地址中...
userscript.html?id=0ba05d47-bf94-40ba-9cca-5eb1fc2e3927:175 debug: ajax: https://www.biliplus.com/BPplayurl.php?cid=34210729&appkey=84956560bc028eb7…&module=bangumi&season_type=1&qn=112&sign=641fa10867cc85f1b422d4afef61a62d
userscript.html?id=0ba05d47-bf94-40ba-9cca-5eb1fc2e3927:897 GET https://www.biliplus.com/BPplayurl.php?cid=34210729&appkey=84956560bc028eb7…&module=bangumi&season_type=1&qn=112&sign=641fa10867cc85f1b422d4afef61a62d net::ERR_TIMED_OUT
value @ userscript.html?id=0ba05d47-bf94-40ba-9cca-5eb1fc2e3927:897
send @ jquery.min.js:4
ajax @ jquery.min.js:4
$.ajax @ userscript.html?id=0ba05d47-bf94-40ba-9cca-5eb1fc2e3927:1021
t.ajax @ comment.min.js:1
e.ajax @ bilibiliPlayer.min.js?v=6b8deee3:260
(anonymous) @ userscript.html?id=0ba05d47-bf94-40ba-9cca-5eb1fc2e3927:487
util_ajax @ userscript.html?id=0ba05d47-bf94-40ba-9cca-5eb1fc2e3927:475
_asyncAjax @ userscript.html?id=0ba05d47-bf94-40ba-9cca-5eb1fc2e3927:1323
asyncAjax @ userscript.html?id=0ba05d47-bf94-40ba-9cca-5eb1fc2e3927:1380
$.ajax @ userscript.html?id=0ba05d47-bf94-40ba-9cca-5eb1fc2e3927:1000
t.ajax @ comment.min.js:1
e.ajax @ bilibiliPlayer.min.js?v=6b8deee3:260
(anonymous) @ bilibiliPlayer.min.js?v=6b8deee3:1093
aI @ bilibiliPlayer.min.js?v=6b8deee3:1366
e @ bilibiliPlayer.min.js?v=6b8deee3:1384
n.(anonymous function) @ bilibiliPlayer.min.js?v=6b8deee3:1422
e @ bilibiliPlayer.min.js?v=6b8deee3:1383
ha @ bilibiliPlayer.min.js?v=6b8deee3:1422
dynCall_vi @ bilibiliPlayer.min.js?v=6b8deee3:1424
rr @ bilibiliPlayer.min.js?v=6b8deee3:1119
(anonymous) @ bilibiliPlayer.min.js?v=6b8deee3:1120
e @ bilibiliPlayer.min.js?v=6b8deee3:1366
(anonymous) @ bilibiliPlayer.min.js?v=6b8deee3:1110
userscript.html?id=0ba05d47-bf94-40ba-9cca-5eb1fc2e3927:175 log: player msg: {"readyState":0,"responseText":"","status":0,"statusText":"error"}
userscript.html?id=0ba05d47-bf94-40ba-9cca-5eb1fc2e3927:175 log: player msg: 尝试换用B站接口拉取视频地址(清晰度低)...
userscript.html?id=0ba05d47-bf94-40ba-9cca-5eb1fc2e3927:175 debug: ajax: https://interface.bilibili.com/playurl?cid=34210729&player=1&qn=112&quality=112&ts=1522043746&sign=e8aa2316a36f524e8abde2ca99a20377
userscript.html?id=0ba05d47-bf94-40ba-9cca-5eb1fc2e3927:175 log: player msg: {"readyState":4,"responseText":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n<video>\r\n   <result>error</result>\r\n   <code>10004</code>\r\n   <message><![CDATA[Video is hidden.]]></message>\r\n","status":200,"statusText":"OK"}
ep115394:1 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'length' of undefined
    at Object.m.handlePlayUrl (chrome-extension://kpbnombpnpcffllnianjibmpadjolanh/bilibili_injected.min.js:1:3357)
    at chrome-extension://kpbnombpnpcffllnianjibmpadjolanh/bilibili_injected.min.js:1:5896
userscript.html?id=0ba05d47-bf94-40ba-9cca-5eb1fc2e3927:897 GET https://api.bilibili.com/x/web-show/res/loc?pf=0&id=160&aid=20877830&jsonp=jsonp net::ERR_BLOCKED_BY_CLIENT
value @ userscript.html?id=0ba05d47-bf94-40ba-9cca-5eb1fc2e3927:897
send @ jquery.min.js:4
ajax @ jquery.min.js:4
$.ajax @ userscript.html?id=0ba05d47-bf94-40ba-9cca-5eb1fc2e3927:1021
t.ajax @ comment.min.js:1
e.ajax @ bilibiliPlayer.min.js?v=6b8deee3:260
c.getData @ bilibiliPlayer.min.js?v=6b8deee3:1503
(anonymous) @ bilibiliPlayer.min.js?v=6b8deee3:1495
c.qe @ bilibiliPlayer.min.js?v=6b8deee3:859
e.ob @ bilibiliPlayer.min.js?v=6b8deee3:209
d.m @ bilibiliPlayer.min.js?v=6b8deee3:1495
d @ bilibiliPlayer.min.js?v=6b8deee3:1494
(anonymous) @ bilibiliPlayer.min.js?v=6b8deee3:206
dispatch @ jquery.min.js:3
i @ jquery.min.js:3
trigger @ jquery.min.js:3
(anonymous) @ jquery.min.js:3
each @ jquery.min.js:2
each @ jquery.min.js:2
trigger @ jquery.min.js:3
e.trigger @ bilibiliPlayer.min.js?v=6b8deee3:218
(anonymous) @ bilibiliPlayer.min.js?v=6b8deee3:255

<!-- 如果脚本崩溃, 连日志都不能导出Σ( ￣□￣||), 则把 控制台截图 放到下面 -->

## 其他

1. 浏览器版本：猎豹
2. 国家/地区：中国

**Comment by ipcjs** [comment]
能打开 https://www.biliplus.com 吗？

**Comment by Cathyyin** [comment]
QAQ打不开

**Comment by ouyang-yuxuan** [comment]
我的也不行了，用不了了

**Comment by FlandreDaisuki** [comment]
試了幾分鐘才成功看片
- - -
連 http://www.biliplus.com 首頁的幾個 timing record

![_001](https://user-images.githubusercontent.com/5981459/37974249-0421ec40-320f-11e8-942b-3477bf52e77f.png)
![_002](https://user-images.githubusercontent.com/5981459/37974250-04566eac-320f-11e8-9a8e-7916df8181fa.png)
![_003](https://user-images.githubusercontent.com/5981459/37974251-048f11e4-320f-11e8-8c5c-2d4e952b6aea.png)

/cc @esterTion

**Comment by esterTion** [comment]
我往本地拖数据库，拖了一晚上下了三遍还是损坏
怕是有毒
这会儿应该不卡了

**Comment by Cathyyin** [comment]
@ipcjs 大佬QAQ help~~~

**Comment by ipcjs** [comment]
@Cathyyin 不是脚本的问题，设置里的两个服务器换着用试试
