### ISSUE TITLE
脚本无法加载 error:ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by yuanyao56** [ipcjs/bilibili-helper#294]
## 描述
error:ReferenceError: $ is not defined
显示视频不存在

- 问题网址：
https://www.bilibili.com/video/av34043619/

## 日志

<details>
<summary>Verbose 日志</summary>

```
点击“设置 > 复制日志”，将导出的日志，粘贴在这里
（设置按钮在番剧页面的右下角，是一个“土星”图标）

```
 
</details>

log: [解除B站区域限制 v6.9.6 (Tampermonkey)] run on: https://www.bilibili.com/video/av34043619/
userscript.html?id=c…ad-cd839abc5ef5:189 log: mode: default blocked_vip: undefined server: https://www.biliplus.com upos_server: undefined flv_prefer_ws:  remove_pre_ad: undefined readyState: loading isLogin: true isLoginBiliBili: true
userscript.html?id=c…ad-cd839abc5ef5:189 log: error: 
Arguments(1)
0: ReferenceError: $ is not defined at eval (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=cd884d56-7d37-47c1-b0ad-cd839abc5ef5:501:13) at new Promise (<anonymous>) at util_ajax (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=cd884d56-7d37-47c1-b0ad-cd839abc5ef5:489:16) at balh_api_plus_view (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=cd884d56-7d37-47c1-b0ad-cd839abc5ef5:887:16) at tryRedirectToBangumiOrInsertPlayer (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=cd884d56-7d37-47c1-b0ad-cd839abc5ef5:1717:13) at Object.util_init (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=cd884d56-7d37-47c1-b0ad-cd839abc5ef5:1848:17) at Object.eval [as func] (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=cd884d56-7d37-47c1-b0ad-cd839abc5ef5:204:29) at callbacks.(anonymous function).sort.filter.forEach.item (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=cd884d56-7d37-47c1-b0ad-cd839abc5ef5:251:43) at Array.forEach (<anonymous>) at HTMLDocument.dcl (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=cd884d56-7d37-47c1-b0ad-cd839abc5ef5:251:22)
message: "$ is not defined"
stack: "ReferenceError: $ is not defined↵    at eval (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=cd884d56-7d37-47c1-b0ad-cd839abc5ef5:501:13)↵    at new Promise (<anonymous>)↵    at util_ajax (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=cd884d56-7d37-47c1-b0ad-cd839abc5ef5:489:16)↵    at balh_api_plus_view (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=cd884d56-7d37-47c1-b0ad-cd839abc5ef5:887:16)↵    at tryRedirectToBangumiOrInsertPlayer (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=cd884d56-7d37-47c1-b0ad-cd839abc5ef5:1717:13)↵    at Object.util_init (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=cd884d56-7d37-47c1-b0ad-cd839abc5ef5:1848:17)↵    at Object.eval [as func] (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=cd884d56-7d37-47c1-b0ad-cd839abc5ef5:204:29)↵    at callbacks.(anonymous function).sort.filter.forEach.item (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=cd884d56-7d37-47c1-b0ad-cd839abc5ef5:251:43)↵    at Array.forEach (<anonymous>)↵    at HTMLDocument.dcl (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?id=cd884d56-7d37-47c1-b0ad-cd839abc5ef5:251:22)"
__proto__: Error
callee: (...)
length: 1
Symbol(Symbol.iterator): ƒ values()
get callee: ƒ ()
set callee: ƒ ()
__proto__: Object

Uncaught DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.131d13ad919a853787d354bebf6f13421ba7b426.js:7:38084)
    at p (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.131d13ad919a853787d354bebf6f13421ba7b426.js:7:53309)
    at f (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.131d13ad919a853787d354bebf6f13421ba7b426.js:7:52943)
    at h (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.131d13ad919a853787d354bebf6f13421ba7b426.js:7:53392)
    at A (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.131d13ad919a853787d354bebf6f13421ba7b426.js:7:56679)
    at A (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.131d13ad919a853787d354bebf6f13421ba7b426.js:7:56614)
    at A (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.131d13ad919a853787d354bebf6f13421ba7b426.js:7:56614)
    at A (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.131d13ad919a853787d354bebf6f13421ba7b426.js:7:56614)
    at A (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.131d13ad919a853787d354bebf6f13421ba7b426.js:7:56614)
    at a.__patch__ (https://s1.hdslb.com/bfs/static/jinkela/video/stardust-video.131d13ad919a853787d354bebf6f13421ba7b426.js:7:57033)
## 其他

1. 浏览器版本：chrome 69.0.3497.100
2. 国家/地区：美国

**Comment by ipcjs** [comment]
检查更新
