### ISSUE TITLE
无法成功登录和登出b站帐号，1080p的也看不了

### ISSUE THREAD

**Issue by qmc1020** [ipcjs/bilibili-helper#72]
## 描述

我想登录我的b站帐号（有大会员）看1080P，但是并不能登录，然后登出也不行。 用网页上右下的不行，手打bangumi_area_limit_hack.logout()，bangumi_area_limit_hack.login()也不行。进这个网址也不行。
不过不管哪一个办法进去的都是一样的页面，然后都不行。

## 日志

```
<!-- 复制来的日志，粘贴在这里 -->
打入bangumi_area_limit_hack.logout()后页面显示：

感谢使用，正在为您清除登录cookie
访问key删除失败，错误：[403]undefined



打入bangumi_area_limit_hack.login()后，刚进入页面还没点授权就出现了以下的log：
VM269 geetest.6.0.9.js:1 Uncaught ReferenceError: errors is not defined
    at Object.v7B.(anonymous function) [as Wa] (https://static.geetest.com/static/js/geetest.6.0.9.js:1:90988)
    at k7B.v7B.(anonymous function) (https://static.geetest.com/static/js/geetest.6.0.9.js:1:97923)
    at k7B.<anonymous> (https://static.geetest.com/static/js/geetest.6.0.9.js:1:108015)
    at Object.n7B.(anonymous function) [as I] (https://static.geetest.com/static/js/geetest.6.0.9.js:1:181400)
    at https://static.geetest.com/static/js/geetest.6.0.9.js:1:78846
    at https://static.geetest.com/static/js/geetest.6.0.9.js:1:203044
    at https://static.geetest.com/static/js/geetest.6.0.9.js:1:78247
    at r8W (https://static.geetest.com/static/js/geetest.6.0.9.js:1:196533)
    at HTMLLinkElement.M0B.Y8W.(anonymous function) (https://static.geetest.com/static/js/geetest.6.0.9.js:1:193881)
v7B.(anonymous function) @ VM269 geetest.6.0.9.js:1
v7B.(anonymous function) @ VM269 geetest.6.0.9.js:1
(anonymous) @ VM269 geetest.6.0.9.js:1
n7B.(anonymous function) @ VM269 geetest.6.0.9.js:1
(anonymous) @ VM269 geetest.6.0.9.js:1
(anonymous) @ VM269 geetest.6.0.9.js:1
(anonymous) @ VM269 geetest.6.0.9.js:1
r8W @ VM269 geetest.6.0.9.js:1
M0B.Y8W.(anonymous function) @ VM269 geetest.6.0.9.js:1
VM269 geetest.6.0.9.js:1 Uncaught ReferenceError: errors is not defined
    at Object.v7B.(anonymous function) [as Wa] (https://static.geetest.com/static/js/geetest.6.0.9.js:1:90988)
    at k7B.v7B.(anonymous function) (https://static.geetest.com/static/js/geetest.6.0.9.js:1:97923)
    at k7B.<anonymous> (https://static.geetest.com/static/js/geetest.6.0.9.js:1:108015)
    at Object.n7B.(anonymous function) [as I] (https://static.geetest.com/static/js/geetest.6.0.9.js:1:181400)
    at https://static.geetest.com/static/js/geetest.6.0.9.js:1:78846
    at https://static.geetest.com/static/js/geetest.6.0.9.js:1:203044
    at https://static.geetest.com/static/js/geetest.6.0.9.js:1:78571
之后点击授权后， 页面显示：存储失败：网络错误。重试次数超过3次，登录失败




```

## 其他

1. 浏览器版本：chrome最新
2. 国家/地区：加拿大

**Comment by ipcjs** [comment]
还有这个问题么？

**Comment by ipcjs** [comment]
不能登出是bug，详见 #68 
不能登录大概是服务器的问题？你现在再试下？

**Comment by qmc1020** [comment]
已经解决了， 我之前过了一周又试了一下。一下子就没问题了
